
local M = {}

M.DEBUG = true

-- main_controller
M.BOOT_SCENE = "menu" -- default: "menu"

-- arena
M.ARENA_SIZE = 2000
M.STARS_COUNT = 800
M.BORDER_SEGMENTS = 100
M.BORDER_ROTATION = 90
M.GAME_TIME = 180

-- border
M.FIELD_POWER = 2
M.FIELD_RADIUS = 200

-- bullet
M.BULLET_SPEED = 1500
M.BULLET_DISTANCE = 1000

-- camera
M.CAMERA_ALTITUDE = 1000
M.ZOOM_MIN = 0.4 -- fixed at 0.2 if DEBUG true
M.ZOOM_MAX = 0.8
M.ZOOM_FACTOR = 1.3
M.ZOOM_TIMER = 0.8
M.ZOOM_TRANSITION = 0.05

-- enemy
M.CHASE_DIST_START = 800
M.CHASE_DIST_STOP = 1100
M.CHASE_DIST_TARGET = 400
M.ENEMY_HEALTH = 3
M.ENEMY_SPEED = 400
M.ENEMY_FIRE_RANGE = 700
M.ENEMY_FIRE_RATE = 2

-- ship
M.VELOCITY_TERMINAL = 30
M.IMPULSE_STRENGTH = 1.2 -- collision restitution
M.HEALTH_MAX = 5
M.AMMO_START = 300
M.SPEED_MAX = 20
M.FRICTION_LINEAR = 0.5
M.ROTATE_POWER = 9
M.ROTATE_DECEL = 3
M.THRUST_FWD = 0.5
M.THRUST_BWD = 0.3
M.THRUST_LAT = 0.2
M.THRUST_DECEL = 2
M.DAMPER_ROT = 5 -- turn coordination
M.DAMPER_LNG = 1
M.DAMPER_LAT = 3

return M
